# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecmin <- function(x) {
    .Call('_abundancer_vecmin', PACKAGE = 'abundancer', x)
}

vecmax <- function(x) {
    .Call('_abundancer_vecmax', PACKAGE = 'abundancer', x)
}

all_sug <- function(x) {
    .Call('_abundancer_all_sug', PACKAGE = 'abundancer', x)
}

ovln_cpp_old <- function(theo_mz, exp_mz, rp) {
    .Call('_abundancer_ovln_cpp_old', PACKAGE = 'abundancer', theo_mz, exp_mz, rp)
}

ovln_cpp <- function(theo_mz, exp_mz, rp) {
    .Call('_abundancer_ovln_cpp', PACKAGE = 'abundancer', theo_mz, exp_mz, rp)
}

ovlhn_cpp_old <- function(theo_mz_ovlhn, exp_mz_ovlhn, theo_sn_ovlhn, exp_sn_ovlhn, rp_ovlhn) {
    .Call('_abundancer_ovlhn_cpp_old', PACKAGE = 'abundancer', theo_mz_ovlhn, exp_mz_ovlhn, theo_sn_ovlhn, exp_sn_ovlhn, rp_ovlhn)
}

ovlhn_cpp <- function(theo_mz_ovlhn, exp_mz_ovlhn, theo_sn_ovlhn, exp_sn_ovlhn, rp_ovlhn) {
    .Call('_abundancer_ovlhn_cpp', PACKAGE = 'abundancer', theo_mz_ovlhn, exp_mz_ovlhn, theo_sn_ovlhn, exp_sn_ovlhn, rp_ovlhn)
}

ScoreMFA_cpp <- function(vexp_mz, vtheo_mz, vrp, vexp_sn, vtheo_sn) {
    .Call('_abundancer_ScoreMFA_cpp', PACKAGE = 'abundancer', vexp_mz, vtheo_mz, vrp, vexp_sn, vtheo_sn)
}

